apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-2-front
  namespace: homework
  labels:
    app: hw-2-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw-2-front
  template:
    metadata:
      labels:
        app: hw-2-front
    spec:
      initContainers:
      - name: busybox
        image: busybox:1.36.1
        volumeMounts:
        - name: shared-volume
          mountPath: /init
        command: ["/bin/sh", "-c", "echo '<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n</head>\n<body>\n<h1>Ахалай махалай</h1>\n<p>Ляськи масяськи</p>\n</body>\n</html>' > /init/index.html"]
      containers:
      - name: nginx
        image: nginx:1.25.3
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: shared-volume
          mountPath: /homework
        - name: nginx-config-volume
          mountPath: /etc/nginx
          readOnly: true
        lifecycle:
          preStop:
            exec:
              command: ["rm", "-rf", "/homework/index.html"]
        readinessProbe:
          exec:
            command: ["cat", "/homework/index.html"]
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: shared-volume
        emptyDir: {}
      - name: nginx-config-volume
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
      nodeSelector:
        homework: "true"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
