apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-volume-pvc
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: custom-storage-class
