apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.configMap.name }}
  namespace: {{ .Values.namespace.name }}
data:
  nginx.conf: |
    user              nginx;
    worker_processes  auto;
    events {
      worker_connections  1024;
    }
    http {
      server {
          listen      {{ .Values.nginx.port }};
          server_name {{ .Values.host.name }};
          
          location / {
            root  {{ .Values.nginx.basePath }};
            index {{ .Values.nginx.index }};
          }
          
          location = /metrics {
            alias {{ .Values.nginx.basePath }}/{{ .Values.metrics.file.name }};
          }
          
          location = /conf/file {
            alias {{ .Values.nginx.basePath }}{{ .Values.simpleFile.file.path }}/{{ .Values.simpleFile.file.name }};
          }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.simpleFile.configMap.name }}
  namespace: {{ .Values.namespace.name }}
data:
  {{ .Values.simpleFile.file.name }}: |
    "Ahalay": "Mahalay"
    "Lyaski": "Masyaski"
