apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.persistentVolumeClaim.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.storage.class.name }}
