apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    {{- with .Values.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.nginx.port }}
