apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.metrics.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
secrets:
  - name: monitoring
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.metrics.secret.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.metrics.serviceAccount.name }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.metrics.clusterRole.name }}
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.metrics.clusterRoleBinding.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.metrics.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.metrics.clusterRole.name }}
  apiGroup: rbac.authorization.k8s.io
