---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       8000;
          server_name  localhost;
          location / {
            root   /homework;
            index  index.html;
        }
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: hw-1-front
  namespace: homework
  labels:
    app: hw-1-front
spec:
  initContainers:
  - name: busybox
    image: busybox:1.36.1
    volumeMounts:
    - name: shared-volume
      mountPath: /init
    command: ["/bin/sh", "-c", "echo '<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n</head>\n<body>\n<h1>Ахалай махалай</h1>\n<p>Ляськи масяськи</p>\n</body>\n</html>' > /init/index.html"]
  containers:
  - name: nginx
    image: nginx:1.25.3
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: shared-volume
      mountPath: /homework
    - name: nginx-config-volume
      mountPath: /etc/nginx
      readOnly: true
    lifecycle:
      preStop:
        exec:
          command: ["rm", "-rf", "/homework/index.html"]
  volumes:
  - name: shared-volume
    emptyDir: {}
  - name: nginx-config-volume
    configMap:
      name: nginx-config
      items:
        - key: nginx.conf
          path: nginx.conf
